database:
  mysql:
    user: root
    password: 213103
#    host: "1.95.54.11"
#    port: 3307
    host: "127.0.0.1"
    port: 3306
    database: VideoWeb
    charset: utf8mb4
  redis:
#    host: "1.95.54.11"
#    port: 6380
    host: "127.0.0.1"
    port: 6379
    password: ""
    database: 0
log:
  level: "InfoLevel"
  path: "./logs/VideoWeb.log"
  timeFormat: "2006-01-02 15:04:05"