database:
  mysql:
    user: root
    password: 213103
    host: "127.0.0.1"
    port: 3306
    database: VideoWeb
    charset: utf8mb4
  redis:
    host: "127.0.0.1"
    port: 6379
    password: ""
    database: 0